<?php

use Illuminate\Database\Seeder;
use App\Country;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->delete();
        Country::create(['name' => 'Австралия','country_id' => 'AU']);
        Country::create(['name' => 'Австрия','country_id' => 'AT']);
        Country::create(['name' => 'Азербайджан','country_id' => 'AZ']);
        Country::create(['name' => 'Албания','country_id' => 'AL']);
        Country::create(['name' => 'Алжир','country_id' => 'DZ']);
        Country::create(['name' => 'Американское Самоа','country_id' => 'AS']);
        Country::create(['name' => 'Ангола','country_id' => 'AO']);
        Country::create(['name' => 'Ангилья','country_id' => 'AI']);
        Country::create(['name' => 'Андорра','country_id' => 'AD']);
        Country::create(['name' => 'Антарктида','country_id' => 'AQ']);
        Country::create(['name' => 'Антигуа и Барбуда','country_id' => 'AG']);
        Country::create(['name' => 'Аргентина','country_id' => 'AR']);
        Country::create(['name' => 'Армения','country_id' => 'AM']);
        Country::create(['name' => 'Аруба','country_id' => 'AW']);
        Country::create(['name' => 'Афганистан','country_id' => 'AF']);
        Country::create(['name' => 'Багамы','country_id' => 'BS']);
        Country::create(['name' => 'Бангладеш','country_id' => 'BD']);
        Country::create(['name' => 'Барбадос','country_id' => 'BB']);
        Country::create(['name' => 'Бахрейн','country_id' => 'BH']);
        Country::create(['name' => 'Белиз','country_id' => 'BZ']);
        Country::create(['name' => 'Белоруссия','country_id' => 'BY']);
        Country::create(['name' => 'Бельгия','country_id' => 'BE']);
        Country::create(['name' => 'Бенин','country_id' => 'BJ']);
        Country::create(['name' => 'Бермуды','country_id' => 'BM']);
        Country::create(['name' => 'Болгария','country_id' => 'BG']);
        Country::create(['name' => 'Боливия','country_id' => 'BO']);
        Country::create(['name' => 'Босния и Герцеговина','country_id' => 'BA']);
        Country::create(['name' => 'Ботсвана','country_id' => 'BW']);
        Country::create(['name' => 'Бразилия','country_id' => 'BR']);
        Country::create(['name' => 'Британская территория в Индийском океане','country_id' => 'IO']);
        Country::create(['name' => 'Бруней','country_id' => 'BN']);
        Country::create(['name' => 'Буркина-Фасо','country_id' => 'BF']);
        Country::create(['name' => 'Бурунди','country_id' => 'BI']);
        Country::create(['name' => 'Бутан','country_id' => 'BT']);
        Country::create(['name' => 'Ватикан','country_id' => 'VA']);
        Country::create(['name' => 'Венгрия','country_id' => 'HU']);
        Country::create(['name' => 'Венесуэла','country_id' => 'VE']);
        Country::create(['name' => 'Вьетнам','country_id' => 'VN']);
        Country::create(['name' => 'Габон','country_id' => 'GA']);
        Country::create(['name' => 'Гаити','country_id' => 'HT']);
        Country::create(['name' => 'Гайана','country_id' => 'GY']);
        Country::create(['name' => 'Гамбия','country_id' => 'GM']);
        Country::create(['name' => 'Гана','country_id' => 'GH']);
        Country::create(['name' => 'Гваделупа','country_id' => 'GP']);
        Country::create(['name' => 'Гватемала','country_id' => 'GT']);
        Country::create(['name' => 'Гвинея','country_id' => 'GN']);
        Country::create(['name' => 'Германия','country_id' => 'DE']);
        Country::create(['name' => 'Гибралтар','country_id' => 'GI']);
        Country::create(['name' => 'Гондурас','country_id' => 'HN']);
        Country::create(['name' => 'Гонконг','country_id' => 'HK']);
        Country::create(['name' => 'Гренада','country_id' => 'GD']);
        Country::create(['name' => 'Гренландия','country_id' => 'GL']);
        Country::create(['name' => 'Греция','country_id' => 'GR']);
        Country::create(['name' => 'Грузия','country_id' => 'GE']);
        Country::create(['name' => 'Гуам','country_id' => 'GU']);
        Country::create(['name' => 'Дания','country_id' => 'DK']);
        Country::create(['name' => 'Доминика','country_id' => 'DM']);
        Country::create(['name' => 'Доминиканская Республика','country_id' => 'DO']);
        Country::create(['name' => 'Египет','country_id' => 'EG']);
        Country::create(['name' => 'Заир','country_id' => 'ZR']);
        Country::create(['name' => 'Замбия','country_id' => 'ZM']);
        Country::create(['name' => 'Западная Сахара','country_id' => 'EH']);
        Country::create(['name' => 'Зимбабве','country_id' => 'ZW']);
        Country::create(['name' => 'Израиль','country_id' => 'IL']);
        Country::create(['name' => 'Индия','country_id' => 'IN']);
        Country::create(['name' => 'Индонезия','country_id' => 'ID']);
        Country::create(['name' => 'Иордания','country_id' => 'JO']);
        Country::create(['name' => 'Ирак','country_id' => 'IQ']);
        Country::create(['name' => 'Иран','country_id' => 'IR']);
        Country::create(['name' => 'Ирландия','country_id' => 'IE']);
        Country::create(['name' => 'Исландия','country_id' => 'IS']);
        Country::create(['name' => 'Испания','country_id' => 'ES']);
        Country::create(['name' => 'Италия','country_id' => 'IT']);
        Country::create(['name' => 'Йемен','country_id' => 'YE']);
        Country::create(['name' => 'Казахстан','country_id' => 'KZ']);
        Country::create(['name' => 'Острова Кайман','country_id' => 'KY']);
        Country::create(['name' => 'Камбоджа','country_id' => 'KH']);
        Country::create(['name' => 'Камерун','country_id' => 'CM']);
        Country::create(['name' => 'Канада','country_id' => 'CA']);
        Country::create(['name' => 'Катар','country_id' => 'QA']);
        Country::create(['name' => 'Кения','country_id' => 'KE']);
        Country::create(['name' => 'Кипр','country_id' => 'CY']);
        Country::create(['name' => 'Киргизия','country_id' => 'KG']);
        Country::create(['name' => 'Кирибати','country_id' => 'KI']);
        Country::create(['name' => 'Китайская Республика','country_id' => 'TW']);
        Country::create(['name' => 'Колумбия','country_id' => 'CO']);
        Country::create(['name' => 'Коморы','country_id' => 'KM']);
        Country::create(['name' => 'Конго','country_id' => 'CG']);
        Country::create(['name' => 'Корея','country_id' => 'KR']);
        Country::create(['name' => 'Коста-Рика	','country_id' => 'CR']);
        Country::create(['name' => 'Куба','country_id' => 'CU']);
        Country::create(['name' => 'Кувейт','country_id' => 'KW']);
        Country::create(['name' => 'Латвия','country_id' => 'LV']);
        Country::create(['name' => 'Ливан','country_id' => 'LB']);
        Country::create(['name' => 'Либерия','country_id' => 'LR']);
        Country::create(['name' => 'Литва','country_id' => 'LT']);
        Country::create(['name' => 'Лихтенштейн','country_id' => 'LI']);
        Country::create(['name' => 'Люксембург','country_id' => 'LU']);
        Country::create(['name' => 'Маврикий','country_id' => 'MU']);
        Country::create(['name' => 'Мавритания','country_id' => 'MR']);
        Country::create(['name' => 'Мадагаскар','country_id' => 'MG']);
        Country::create(['name' => 'Макао','country_id' => 'MO']);
        Country::create(['name' => 'Македония','country_id' => 'MK']);
        Country::create(['name' => 'Малайзия','country_id' => 'MY']);
        Country::create(['name' => 'Мали','country_id' => 'ML']);
        Country::create(['name' => 'Мальдивы','country_id' => 'MV']);
        Country::create(['name' => 'Мальта','country_id' => 'MT']);
        Country::create(['name' => 'Мексика','country_id' => 'MX']);
        Country::create(['name' => 'Микронезия','country_id' => 'FM']);
        Country::create(['name' => 'Мозамбик','country_id' => 'MZ']);
        Country::create(['name' => 'Молдавия','country_id' => 'MD']);
        Country::create(['name' => 'Монако','country_id' => 'MC']);
        Country::create(['name' => 'Монголия','country_id' => 'MN']);
        Country::create(['name' => 'Монтсеррат','country_id' => 'MS']);
        Country::create(['name' => 'Марокко','country_id' => 'MA']);
        Country::create(['name' => 'Намибия','country_id' => 'NA']);
        Country::create(['name' => 'Науру','country_id' => 'NR']);
        Country::create(['name' => 'Непал','country_id' => 'NP']);
        Country::create(['name' => 'Нигерия','country_id' => 'NG']);
        Country::create(['name' => 'Нидерланды','country_id' => 'NL']);
        Country::create(['name' => 'Никарагуа','country_id' => 'NI']);
        Country::create(['name' => 'Новая Зеландия','country_id' => 'NZ']);
        Country::create(['name' => 'Норвегия','country_id' => 'NO']);
        Country::create(['name' => 'ОАЭ','country_id' => 'AE']);
        Country::create(['name' => 'Оман','country_id' => 'OM']);
        Country::create(['name' => 'Остров Мэн','country_id' => 'IM']);
        Country::create(['name' => 'Острова Кука','country_id' => 'CK']);
        Country::create(['name' => 'Острова Святой Елены, Вознесения и Тристан-да-Кунья','country_id' => 'SH']);
        Country::create(['name' => 'Пакистан','country_id' => 'PK']);
        Country::create(['name' => 'Панама','country_id' => 'PA']);
        Country::create(['name' => 'Парагвай','country_id' => 'PY']);
        Country::create(['name' => 'Перу','country_id' => 'PE']);
        Country::create(['name' => 'Польша','country_id' => 'PL']);
        Country::create(['name' => 'Португалия','country_id' => 'PT']);
        Country::create(['name' => 'Пуэрто-Рико','country_id' => 'PR']);
        Country::create(['name' => 'Россия','country_id' => 'RU']);
        Country::create(['name' => 'Руанда','country_id' => 'RW']);
        Country::create(['name' => 'Румыния','country_id' => 'RO']);
        Country::create(['name' => 'Самоа','country_id' => 'WS']);
        Country::create(['name' => 'Сан-Марино','country_id' => 'SM']);
        Country::create(['name' => 'Саудовская Аравия','country_id' => 'SA']);
        Country::create(['name' => 'Свазиленд','country_id' => 'SZ']);
        Country::create(['name' => 'Северная Корея','country_id' => 'KP']);
        Country::create(['name' => 'Сейшельские Острова	','country_id' => 'SC']);
        Country::create(['name' => 'Сенегал','country_id' => 'SN']);
        Country::create(['name' => 'Сербия','country_id' => 'RS']);
        Country::create(['name' => 'Сингапур','country_id' => 'SG']);
        Country::create(['name' => 'Словакия','country_id' => 'SK']);
        Country::create(['name' => 'Словения','country_id' => 'SI']);
        Country::create(['name' => 'Соломоновы Острова','country_id' => 'SB']);
        Country::create(['name' => 'Сомали','country_id' => 'SO']);
        Country::create(['name' => 'Судан','country_id' => 'SD']);
        Country::create(['name' => 'США','country_id' => 'US']);
        Country::create(['name' => 'Соединённое королевство','country_id' => 'GB']);
        Country::create(['name' => 'Суринам','country_id' => 'SR']);
        Country::create(['name' => 'Таджикистан','country_id' => 'TJ']);
        Country::create(['name' => 'Таиланд','country_id' => 'TH']);
        Country::create(['name' => 'Танзания','country_id' => 'TZ']);
        Country::create(['name' => 'Тайвань','country_id' => 'TW']);
        Country::create(['name' => 'Того','country_id' => 'TG']);
        Country::create(['name' => 'Тонга','country_id' => 'TO']);
        Country::create(['name' => 'Тринидад и Тобаго','country_id' => 'TT']);
        Country::create(['name' => 'Тувалу','country_id' => 'TV']);
        Country::create(['name' => 'Тунис','country_id' => 'TN']);
        Country::create(['name' => 'Туркмения','country_id' => 'TM']);
        Country::create(['name' => 'Турция','country_id' => 'TR']);
        Country::create(['name' => 'Уганда','country_id' => 'UG']);
        Country::create(['name' => 'Узбекистан','country_id' => 'UZ']);
        Country::create(['name' => 'Украина','country_id' => 'UA']);
        Country::create(['name' => 'Уругвай','country_id' => 'UY']);
        Country::create(['name' => 'Фиджи','country_id' => 'FJ']);
        Country::create(['name' => 'Филиппины','country_id' => 'PH']);
        Country::create(['name' => 'Финляндия','country_id' => 'FI']);
        Country::create(['name' => 'Франция','country_id' => 'FR']);
        Country::create(['name' => 'Хорватия','country_id' => 'HR']);
        Country::create(['name' => 'ЦАР','country_id' => 'CF']);
        Country::create(['name' => 'Чад','country_id' => 'TD']);
        Country::create(['name' => 'Черногория','country_id' => 'ME']);
        Country::create(['name' => 'Чехия','country_id' => 'CZ']);
        Country::create(['name' => 'Чили','country_id' => 'CL']);
        Country::create(['name' => 'Швейцария','country_id' => 'CH']);
        Country::create(['name' => 'Швеция','country_id' => 'SE']);
        Country::create(['name' => 'Шри-Ланка','country_id' => 'LK']);
        Country::create(['name' => 'Эквадор','country_id' => 'EC']);
        Country::create(['name' => 'Экваториальная Гвинея','country_id' => 'GQ']);
        Country::create(['name' => 'Эритрея','country_id' => 'ER']);
        Country::create(['name' => 'Эстония','country_id' => 'EE']);
        Country::create(['name' => 'Эфиопия','country_id' => 'ET']);
        Country::create(['name' => 'ЮАР','country_id' => 'ZA']);
        Country::create(['name' => 'Югославия','country_id' => 'YU']);
        Country::create(['name' => 'Южная Георгия и Южные Сандвичевы Острова','country_id' => 'GS']);
        Country::create(['name' => 'Ямайка','country_id' => 'JM']);
        Country::create(['name' => 'Япония','country_id' => 'JP']);
    }
}